
import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Bell, CalendarDays, Check, Gamepad2, Home, Palette, Plus, User, Users, X, Zap } from "lucide-react";
import "./style.css";

const themes = [
  { id: "immersion", label: "Full Immersion", desc: "Cinematic adventure", icon: "🌌" },
  { id: "carousel", label: "Carousel", desc: "Game artwork first", icon: "🎞️" },
  { id: "neon", label: "Neon", desc: "Purple/cyan glow", icon: "⚡" },
  { id: "deck", label: "Steam Deck", desc: "Console focused", icon: "🎮" },
  { id: "arcade", label: "Arcade", desc: "Retro cyber", icon: "👾" },
  { id: "lan", label: "LAN", desc: "Hardware orange", icon: "🖥️" },
  { id: "grid", label: "Grid", desc: "Tactical data", icon: "▦" }
];
const squad = [
  { id: 1, name: "Kevin", avatar: "🛡️", role: "Tactical Vanguard", status: "Playing", game: "Helldivers 2", badges: ["Reliable", "No Fear"], bio: "Komt snel online en joined meestal direct." },
  { id: 2, name: "Tom", avatar: "🧙", role: "Arcane Strategist", status: "In Game", game: "Deep Rock", badges: ["Planner", "Lore Brain"], bio: "Denkt altijd net iets te lang na over builds." },
  { id: 3, name: "Sven", avatar: "🤖", role: "LAN Engineer", status: "In Voice", game: "Discord", badges: ["Cable Goblin", "Tech Support"], bio: "Heeft altijd een kabel, soms zelfs de juiste." },
  { id: 4, name: "Shane", avatar: "🚀", role: "Squad Captain", status: "Browsing", game: "SquadUp.gg", badges: ["Pathfinder", "LAN Lord"], bio: "Start het avontuur en plant de chaos." },
  { id: 5, name: "Lars", avatar: "🐺", role: "Chaos Ranger", status: "Online", game: "Steam", badges: ["Loot Goblin", "Last Minute"], bio: "Komt laat binnen en maakt het alsnog legendarisch." }
];
const avatars = ["🛡️","🧙","🤖","🚀","🐺","🐉","👾","🦾","🧟","🧛","🧝","🦊","🦁","🐲","🦅","🦇","🦄","🦖","⚔️","🏹","🔮","💀","👑","🧠","🔧","💣","🪓","🛸","🕹️","🎮","🔥","⚡","🌙","🐸","🐼","🐵","🐧","🦉","🦈","🐙","🦀"];
const games = [
  {id:1,name:"HELLDIVERS™ 2",match:93,mode:"Co-op PvE",pvp:false,pve:true,coop:true,solo:false,max:4,session:"30-60 min",owned:[1,2,3,4],installed:[1,2,4],want:[5],art:"https://images.unsplash.com/photo-1517976487492-5750f3195933?auto=format&fit=crop&w=1200&q=80",desc:"Co-op chaos met korte missies, duidelijke rollen en veel squad momentum. Perfect wanneer de groep snel iets wil spelen zonder lange voorbereiding."},
  {id:2,name:"DEEP ROCK GALACTIC",match:88,mode:"Co-op PvE",pvp:false,pve:true,coop:true,solo:true,max:4,session:"45-90 min",owned:[1,2,3,4,5],installed:[1,2,3,4],want:[],art:"https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1200&q=80",desc:"Mijnbouw, teamwork en paniek in compacte co-op sessies. Sterk voor korte avonden waarin iedereen snel mee kan doen."},
  {id:3,name:"VALHEIM",match:82,mode:"Survival Co-op",pvp:true,pve:true,coop:true,solo:true,max:10,session:"2+ uur",owned:[1,2,4,5],installed:[2,4],want:[3],art:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",desc:"Survival, bouwen, boss fights en langlopende squad progressie. Goed voor een gedeelde wereld waar je vaker naar terugkeert."},
  {id:4,name:"PROJECT ZOMBOID",match:78,mode:"Survival PvE/PvP",pvp:true,pve:true,coop:true,solo:true,max:16,session:"2+ uur",owned:[1,3,5],installed:[3,5],want:[2,4],art:"https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1200&q=80",desc:"Hardcore survival sandbox voor inside jokes en rampzalige plannen. Minder casual, maar extreem goed voor verhalen."},
  {id:5,name:"RISK OF RAIN 2",match:86,mode:"Co-op Roguelike",pvp:false,pve:true,coop:true,solo:true,max:4,session:"30-75 min",owned:[1,2,4],installed:[1,4],want:[3,5],art:"https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",desc:"Snelle roguelike runs voor avonden met weinig setup. Actiegericht, herspeelbaar en makkelijk opnieuw te starten."}
];
function App(){
 const [theme,setTheme]=useState("neon"); const [selectedGame,setSelectedGame]=useState(null); const [selectedUser,setSelectedUser]=useState(null); const [partyOpen,setPartyOpen]=useState(false); const [partyGame,setPartyGame]=useState(games[0]); const [avatarOpen,setAvatarOpen]=useState(false); const [themeOpen,setThemeOpen]=useState(false); const [myAvatar,setMyAvatar]=useState("🚀"); const [activeTab,setActiveTab]=useState("home"); const [toast,setToast]=useState(""); const [events,setEvents]=useState([{id:1,title:"Helldivers 2 chaos run",time:"Vanavond 20:00",game:"HELLDIVERS™ 2",ready:3}]); const [activity,setActivity]=useState(["Kevin started Helldivers 2","Tom joined voice","Shane opened SquadUp"]); const [partySlots,setPartySlots]=useState([squad[3],squad[0],null,null]); const [ready,setReady]=useState({4:true,1:true}); const [mood,setMood]=useState("Chaos Run"); const [status,setStatus]=useState("Forming"); const [quickOpen,setQuickOpen]=useState(false); const [gameStatus,setGameStatus]=useState({}); const smartGame=games[0];
 function push(message){setToast(message);setActivity(prev=>[message,...prev].slice(0,7));clearTimeout(window.__toast);window.__toast=setTimeout(()=>setToast(""),1600)}
 function openParty(game=smartGame){setPartyGame(game);const size=Math.min(Math.max(game.max,4),6);const initial=[squad[3],...game.owned.map(id=>squad.find(u=>u.id===id)).filter(Boolean).slice(0,size-1)];const unique=Array.from(new Map(initial.map(u=>[u.id,u])).values()).slice(0,size);setPartySlots(Array.from({length:size},(_,i)=>unique[i]||null));setReady(Object.fromEntries(unique.map((u,i)=>[u.id,i<2])));setPartyOpen(true)}
 function addToParty(user){setPartySlots(prev=>{if(prev.some(slot=>slot?.id===user.id))return prev;const next=[...prev];const index=next.findIndex(slot=>slot===null);if(index!==-1)next[index]=user;return next});push(`${user.name} added to party`)}
 function removeSlot(index){setPartySlots(prev=>prev.map((slot,i)=>i===index?null:slot))}
 function toggleReady(id){setReady(prev=>({...prev,[id]:!prev[id]}))}
 function planGame(game){setEvents(prev=>[{id:Date.now(),title:`${game.name} squad night`,time:"Vandaag 20:30",game:game.name,ready:partySlots.filter(Boolean).length},...prev]);push(`${game.name} gepland`)}
 function sendInvites(){const count=partySlots.filter(Boolean).length;setStatus("Ready Check");push(`Invites sent to ${count} players`)}
 function launchGame(){const filled=partySlots.filter(Boolean);const ok=filled.length>0&&filled.every(user=>ready[user.id]);if(!ok){push("Nog niet iedereen is ready");return}setStatus("In Match");push(`${partyGame.name} launched`)}
 function updateGameStatus(gameId,key){setGameStatus(prev=>({...prev,[gameId]:{...(prev[gameId]||{}),[key]:!(prev[gameId]?.[key])}}));push(`${key} bijgewerkt`)}
 const common={theme,setTheme,squad,games,smartGame,openParty,setSelectedGame,setSelectedUser,events,activity,myAvatar,setAvatarOpen,setThemeOpen,push,planGame};
 return <div className={`app theme-${theme}`}><DesktopView {...common}/><main className="mobileView"><MobileLayout {...common}/><NavDock activeTab={activeTab} setActiveTab={setActiveTab} openParty={()=>openParty(smartGame)} setQuickOpen={setQuickOpen} partyCount={partySlots.filter(Boolean).length}/></main>{selectedGame&&<GameModal game={selectedGame} squad={squad} close={()=>setSelectedGame(null)} openParty={openParty} planGame={planGame} status={gameStatus[selectedGame.id]||{}} updateGameStatus={updateGameStatus}/>} {selectedUser&&<UserModal user={selectedUser} close={()=>setSelectedUser(null)} addToParty={addToParty} openParty={()=>openParty(partyGame)}/>} {partyOpen&&<PartyView game={partyGame} setPartyGame={setPartyGame} games={games} squad={squad} slots={partySlots} addToParty={addToParty} removeSlot={removeSlot} ready={ready} toggleReady={toggleReady} mood={mood} setMood={setMood} status={status} sendInvites={sendInvites} launchGame={launchGame} planGame={planGame} close={()=>setPartyOpen(false)}/>} {avatarOpen&&<AvatarModal avatar={myAvatar} setAvatar={setMyAvatar} close={()=>setAvatarOpen(false)} push={push}/>} {themeOpen&&<ThemeDrawer theme={theme} setTheme={setTheme} close={()=>setThemeOpen(false)}/>} {quickOpen&&<QuickMenu close={()=>setQuickOpen(false)} openParty={()=>openParty(smartGame)} setActiveTab={setActiveTab} push={push} setThemeOpen={setThemeOpen}/>}<div className={`toast ${toast?"show":""}`}>{toast}</div></div>
}
function MobileLayout(props){const {theme}=props;if(theme==="carousel")return <CarouselHome {...props}/>;if(theme==="deck")return <DeckHome {...props}/>;if(theme==="arcade")return <ArcadeHome {...props}/>;if(theme==="lan")return <LanHome {...props}/>;if(theme==="grid")return <GridHome {...props}/>;return <section className="screen"><TopBar avatar={props.myAvatar} openAvatar={()=>props.setAvatarOpen(true)} openParty={()=>props.openParty(props.smartGame)} openThemes={()=>props.setThemeOpen(true)}/><Hero game={props.smartGame} openParty={props.openParty} setSelectedGame={props.setSelectedGame}/><SquadRow squad={props.squad} openUser={props.setSelectedUser}/><GameList games={props.games} squad={props.squad} openGame={props.setSelectedGame} openParty={props.openParty}/><Panel title="Planning"><EventList events={props.events}/></Panel><Panel title="Activity"><ActivityList activity={props.activity}/></Panel></section>}
function CarouselHome(props){return <section className="screen"><TopBar avatar={props.myAvatar} openAvatar={()=>props.setAvatarOpen(true)} openParty={()=>props.openParty(props.smartGame)} openThemes={()=>props.setThemeOpen(true)}/><SquadRow squad={props.squad} openUser={props.setSelectedUser} compact/><div className="carouselRail">{props.games.map(game=><button key={game.id} className="carouselCard" onClick={()=>props.setSelectedGame(game)} style={{backgroundImage:`linear-gradient(180deg, transparent, rgba(0,0,0,.82)), url(${game.art})`}}><h2>{game.name}</h2><p>{game.match}% match · {game.mode}</p><span>{game.owned.length}/{props.squad.length} friends own this</span></button>)}</div><Panel title="Planning"><EventList events={props.events}/></Panel></section>}
function DeckHome(props){return <section className="screen deckScreen"><TopBar avatar={props.myAvatar} openAvatar={()=>props.setAvatarOpen(true)} openParty={()=>props.openParty(props.smartGame)} openThemes={()=>props.setThemeOpen(true)}/><h2>Good evening, squad</h2><SquadRow squad={props.squad} openUser={props.setSelectedUser} compact/><button className="wideFeature" onClick={()=>props.openParty(props.games[1])} style={{backgroundImage:`linear-gradient(90deg, rgba(0,0,0,.76), rgba(0,0,0,.2)), url(${props.games[1].art})`}}><small>Continue together</small><strong>{props.games[1].name}</strong></button><GameList games={props.games} squad={props.squad} openGame={props.setSelectedGame} openParty={props.openParty} compact/></section>}
function ArcadeHome(props){return <section className="screen arcadeScreen"><TopBar title="☠ SQUADUP.GG" avatar={props.myAvatar} openAvatar={()=>props.setAvatarOpen(true)} openParty={()=>props.openParty(props.smartGame)} openThemes={()=>props.setThemeOpen(true)}/><div className="arcadePanel"><SquadRow squad={props.squad} openUser={props.setSelectedUser}/></div><button className="startPanel" onClick={()=>props.openParty(props.smartGame)}><h1>WHAT WE PLAYING TONIGHT?</h1><span>PRESS START</span></button><GameList games={props.games} squad={props.squad} openGame={props.setSelectedGame} openParty={props.openParty}/></section>}
function LanHome(props){return <section className="screen lanScreen"><TopBar title="☢ SQUADUP.GG" avatar={props.myAvatar} openAvatar={()=>props.setAvatarOpen(true)} openParty={()=>props.openParty(props.smartGame)} openThemes={()=>props.setThemeOpen(true)}/><button className="terminalPanel" onClick={()=>props.openParty(props.smartGame)}><h1>WHAT ARE WE PLAYING TONIGHT?</h1><p>&gt; START PARTY MODULE</p></button><SquadRow squad={props.squad} openUser={props.setSelectedUser}/><GameList games={props.games} squad={props.squad} openGame={props.setSelectedGame} openParty={props.openParty}/></section>}
function GridHome(props){return <section className="screen gridScreen"><TopBar avatar={props.myAvatar} openAvatar={()=>props.setAvatarOpen(true)} openParty={()=>props.openParty(props.smartGame)} openThemes={()=>props.setThemeOpen(true)}/><div className="gridCards"><Panel title="Squad"><SquadRow squad={props.squad} openUser={props.setSelectedUser} compact/></Panel><Panel title="Mission"><button className="fullButton" onClick={()=>props.openParty(props.smartGame)}>Find match</button></Panel></div><GameList games={props.games} squad={props.squad} openGame={props.setSelectedGame} openParty={props.openParty}/></section>}
function DesktopView(props){const {theme,smartGame,games,squad,openParty,setSelectedGame,setSelectedUser,events,activity,myAvatar,setAvatarOpen,setThemeOpen}=props;return <section className="desktopView"><header className="commandBar"><div className="brand"><Gamepad2/><div><strong>SquadUp<span>.gg</span></strong><small>v0.29 polished</small></div></div><nav className="desktopNav">{["Home","Games","Queue","Squad","Plan","Chat","Profile"].map(label=><button key={label} onClick={()=>label==="Queue"?openParty(smartGame):props.push(`${label} geopend`)}>{label}</button>)}</nav><button className="desktopPlus" onClick={()=>openParty(smartGame)}><Plus/></button><button className="avatarButton" onClick={()=>setAvatarOpen(true)}>{myAvatar}</button><button className="themeButton" onClick={()=>setThemeOpen(true)}><Palette size={18}/>{themes.find(t=>t.id===theme)?.label}</button></header><main className="desktopMain"><section className="smartCards"><button onClick={()=>openParty(smartGame)}><Users/><strong>{squad.length} friends</strong><span>Start squad queue</span></button><button onClick={()=>props.push("Voice mock geopend")}><Bell/><strong>Voice active</strong><span>Join channel</span></button><button onClick={()=>openParty(smartGame)}><CalendarDays/><strong>Next event</strong><span>{events[0]?.time}</span></button></section><Hero game={smartGame} openParty={openParty} setSelectedGame={setSelectedGame} desktop/><div className="desktopGrid"><Panel title="Recommended games"><GameGrid games={games} squad={squad} openGame={setSelectedGame} openParty={openParty}/></Panel><Panel title="Squad online"><SquadList squad={squad} openUser={setSelectedUser}/></Panel><Panel title="Planning"><EventList events={events}/></Panel><Panel title="Activity"><ActivityList activity={activity}/></Panel></div></main></section>}
function TopBar({title="SQUADUP.GG",avatar,openAvatar,openParty,openThemes}){return <header className="topBar"><strong>{title}</strong><div><button onClick={openThemes} aria-label="themes"><Palette size={16}/></button><button onClick={openParty} aria-label="party"><Zap size={16}/></button><button onClick={openAvatar} aria-label="avatar">{avatar}</button></div></header>}
function Hero({game,openParty,setSelectedGame,desktop=false}){return <article className={desktop?"hero desktopHero":"hero"} style={{backgroundImage:`linear-gradient(90deg, rgba(0,0,0,.76), rgba(0,0,0,.18)), url(${game.art})`}}><span>Best match tonight</span><h1>{game.name}</h1><p>{game.desc}</p><ModePills game={game}/><div className="heroActions"><button onClick={()=>openParty(game)}>Open party</button><button onClick={()=>setSelectedGame(game)}>Details</button></div></article>}
function ModePills({game}){return <div className="modePills"><span className={game.pvp?"on":""}>PvP {game.pvp?"yes":"no"}</span><span className={game.pve?"on":""}>PvE {game.pve?"yes":"no"}</span><span className={game.coop?"on":""}>Co-op</span><span className={game.solo?"on":""}>Solo</span></div>}
function SquadRow({squad,openUser,compact=false}){return <div className={compact?"squadRow compact":"squadRow"}>{squad.map(u=><button key={u.id} onClick={()=>openUser(u)}><span>{u.avatar}</span><strong>{u.name}</strong><small>{u.status}</small></button>)}</div>}
function SquadList({squad,openUser}){return <div className="squadList">{squad.map(u=><button key={u.id} onClick={()=>openUser(u)}><span>{u.avatar}</span><div><strong>{u.name}</strong><small>{u.status} · {u.game}</small></div></button>)}</div>}
function GameList({games,squad,openGame,openParty,compact=false}){return <div className={compact?"gameList compact":"gameList"}>{games.slice(0,4).map((game,i)=><article key={game.id} onClick={()=>openGame(game)}><b>{i+1}</b><div className="thumb" style={{backgroundImage:`url(${game.art})`}}/><div><strong>{game.name}</strong><small>{game.match}% · {game.mode}</small><small>{game.owned.length}/{squad.length} own · {game.installed.length} installed</small></div><button onClick={e=>{e.stopPropagation();openParty(game)}}>Party</button></article>)}</div>}
function GameGrid({games,squad,openGame}){return <div className="gameGrid">{games.map(game=><button key={game.id} onClick={()=>openGame(game)} style={{backgroundImage:`linear-gradient(180deg, transparent, rgba(0,0,0,.82)), url(${game.art})`}}><strong>{game.name}</strong><span>{game.match}% · {game.mode}</span><small>{game.owned.length}/{squad.length} own · PvP {game.pvp?"yes":"no"}</small></button>)}</div>}
function Panel({title,children}){return <section className="panel"><div className="panelHead"><h3>{title}</h3></div>{children}</section>}
function EventList({events}){return <div className="eventList">{events.map(e=><article key={e.id}><strong>{e.title}</strong><span>{e.time} · {e.ready} ready</span></article>)}</div>}
function ActivityList({activity}){return <div className="activityList">{activity.map((a,i)=><p key={i}>⚡ {a}</p>)}</div>}
function NavDock({activeTab,setActiveTab,openParty,setQuickOpen,partyCount}){const left=[["home",Home,"Home"],["games",Gamepad2,"Games"],["queue",Zap,"Queue"]];const right=[["plan",CalendarDays,"Plan"],["chat",Bell,"Chat"],["profile",User,"Profile"]];const navButton=([id,Icon,label])=><button key={id} className={activeTab===id?"active":""} onClick={()=>id==="queue"?openParty():setActiveTab(id)}><Icon size={19}/><span>{label}</span>{id==="chat"&&<b>3</b>}</button>;return <nav className="navDock"><div className="navSide left">{left.map(navButton)}</div><button className="centerAction" onClick={()=>setQuickOpen(true)} aria-label="quick actions"><Plus size={30}/><em>{partyCount}/4</em></button><div className="navSide right">{right.map(navButton)}</div></nav>}
function QuickMenu({close,openParty,setActiveTab,push,setThemeOpen}){const actions=[["⚡","Start Queue",openParty],["👥","Create Party",openParty],["📣","Ping Squad",()=>push("Squad ping sent")],["🎨","Change Theme",()=>setThemeOpen(true)],["🎙️","Join Voice",()=>push("Voice opened")],["➕","Add Friend",()=>setActiveTab("squad")]];return <div className="overlay"><section className="quickMenu"><button className="close" onClick={close}><X/></button><h2>Quick actions</h2><div>{actions.map(([icon,label,fn])=><button key={label} onClick={()=>{fn();close()}}><span>{icon}</span><strong>{label}</strong></button>)}</div></section></div>}
function ThemeDrawer({theme,setTheme,close}){return <div className="overlay drawerOverlay"><section className="themeDrawer"><button className="close" onClick={close}><X/></button><span>Layout themes</span><h2>Choose your Squad vibe</h2><div className="themeGrid">{themes.map(item=><button key={item.id} className={theme===item.id?"active":""} onClick={()=>setTheme(item.id)}><i>{item.icon}</i><strong>{item.label}</strong><small>{item.desc}</small></button>)}</div></section></div>}
function GameModal({game,squad,close,openParty,planGame,status,updateGameStatus}){const names=ids=>ids.map(id=>squad.find(u=>u.id===id)?.name).filter(Boolean).join(", ")||"None";return <div className="overlay"><section className="modal"><button className="close" onClick={close}><X/></button><div className="modalBanner" style={{backgroundImage:`linear-gradient(180deg, transparent, rgba(0,0,0,.85)), url(${game.art})`}}><h2>{game.name}</h2><p>{game.mode} · {game.match}% match</p></div><ModePills game={game}/><p>{game.desc}</p><div className="statsGrid"><div><strong>{game.owned.length}/{squad.length}</strong><span>friends own it</span><small>{names(game.owned)}</small></div><div><strong>{game.installed.length}</strong><span>installed</span><small>{names(game.installed)}</small></div><div><strong>{game.want.length}</strong><span>want to buy</span><small>{names(game.want)}</small></div><div><strong>{game.max}</strong><span>max players</span><small>{game.session}</small></div></div><div className="toggleRow">{["owned","want","installed","active"].map(key=><button key={key} className={status[key]?"on":""} onClick={()=>updateGameStatus(game.id,key)}>{status[key]?<Check size={14}/>:null}{key}</button>)}</div><div className="modalActions"><button onClick={()=>openParty(game)}>Open party</button><button onClick={()=>planGame(game)}>Plan night</button></div></section></div>}
function UserModal({user,close,addToParty,openParty}){return <div className="overlay"><section className="modal"><button className="close" onClick={close}><X/></button><div className="profileTop"><span>{user.avatar}</span><div><small>{user.role}</small><h2>{user.name}</h2><p>{user.status} · {user.game}</p></div></div><p>{user.bio}</p><div className="badges">{user.badges.map(b=><em key={b}>{b}</em>)}</div><div className="modalActions"><button onClick={()=>addToParty(user)}>Invite to party</button><button onClick={openParty}>Open party</button></div></section></div>}
function PartyView({game,setPartyGame,games,squad,slots,addToParty,removeSlot,ready,toggleReady,mood,setMood,status,sendInvites,launchGame,planGame,close}){const candidates=squad.filter(u=>!slots.some(s=>s?.id===u.id));const readyCount=slots.filter(s=>s&&ready[s.id]).length;return <div className="overlay partyOverlay"><section className="partyView"><button className="close" onClick={close}><X/></button><header className="partyHero" style={{backgroundImage:`linear-gradient(90deg, rgba(0,0,0,.82), rgba(0,0,0,.2)), url(${game.art})`}}><div><span>Party lobby</span><h1>{game.name}</h1><p>{slots.filter(Boolean).length}/{slots.length} filled · {readyCount} ready · {game.mode}</p><ModePills game={game}/></div><div className="partyStatus"><strong>{status}</strong><small>{mood}</small></div></header><div className="partyBody"><main><div className="partyControls"><select value={game.id} onChange={e=>setPartyGame(games.find(g=>g.id===Number(e.target.value)))}>{games.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><div className="moods">{["Chill","Competitive","Chaos Run","Survival","Quick","All Night"].map(m=><button key={m} className={mood===m?"on":""} onClick={()=>setMood(m)}>{m}</button>)}</div></div><div className="partySlots">{slots.map((slot,i)=><article key={i} className={slot?"slot filled":"slot"}>{slot?<><button className="slotRemove" onClick={()=>removeSlot(i)}>×</button><span>{slot.avatar}</span><strong>{slot.name}</strong><small>{game.owned.includes(slot.id)?"Owns game":"Needs game"} · {game.installed.includes(slot.id)?"Installed":"Needs install"}</small><button className={ready[slot.id]?"ready on":"ready"} onClick={()=>toggleReady(slot.id)}>{ready[slot.id]?"✅ Ready":"🟡 Maybe"}</button></>:<><Plus/><strong>Open slot</strong><small>Invite someone</small></>}</article>)}</div><div className="partyActions"><button onClick={sendInvites}>Send invites</button><button onClick={()=>planGame(game)}>Plan event</button><button className="launch" onClick={launchGame}>Launch game</button></div></main><aside><Panel title="Best invites"><div className="candidateList">{candidates.map(u=><button key={u.id} onClick={()=>addToParty(u)}><span>{u.avatar}</span><div><strong>{u.name}</strong><small>{game.owned.includes(u.id)?"Owns game":"Does not own"} · {u.status}</small></div></button>)}</div></Panel><Panel title="Party feed"><ActivityList activity={["Lobby opened","Ready check available","Voice channel suggested"]}/></Panel></aside></div></section></div>}
function AvatarModal({avatar,setAvatar,close,push}){return <div className="overlay"><section className="modal"><button className="close" onClick={close}><X/></button><h2>Choose avatar</h2><div className="avatarGrid">{avatars.map((a,i)=><button key={`${a}-${i}`} className={avatar===a?"on":""} onClick={()=>{setAvatar(a);push("Avatar gekozen")}}>{a}</button>)}</div></section></div>}
createRoot(document.getElementById("root")).render(<App/>);
