import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Bell, CalendarDays, Gamepad2, Home, Plus, User, Users, X, Zap } from "lucide-react";
import "./style.css";

const themes = ["immersion", "carousel", "neon", "deck", "arcade", "lan", "grid"];
const themeNames = { immersion:"Full Immersion", carousel:"Carousel", neon:"Neon", deck:"Steam Deck", arcade:"Arcade", lan:"LAN", grid:"Grid" };
const squad = [
  { id:1, name:"Kevin", avatar:"🛡️", role:"Tactical Vanguard", status:"Playing", game:"Helldivers 2", badges:["Reliable","No Fear"], bio:"Komt snel online en joined meestal direct." },
  { id:2, name:"Tom", avatar:"🧙", role:"Arcane Strategist", status:"In Game", game:"Deep Rock", badges:["Planner","Lore Brain"], bio:"Denkt altijd net iets te lang na over builds." },
  { id:3, name:"Sven", avatar:"🤖", role:"LAN Engineer", status:"In Voice", game:"Discord", badges:["Cable Goblin","Tech Support"], bio:"Heeft altijd een extra kabel, soms zelfs de juiste." },
  { id:4, name:"Shane", avatar:"🚀", role:"Squad Captain", status:"Browsing", game:"SquadUp.gg", badges:["Pathfinder","LAN Lord"], bio:"Start het avontuur en plant de chaos." },
  { id:5, name:"Lars", avatar:"🐺", role:"Chaos Ranger", status:"Online", game:"Steam", badges:["Loot Goblin","Last Minute"], bio:"Komt laat binnen en maakt het alsnog legendarisch." }
];
const avatars = ["🛡️","🧙","🤖","🚀","🐺","🐉","👾","🦾","🧟","🧛","🧝","🦊","🦁","🐲","🦅","🦇","🦄","🦖","⚔️","🏹","🔮","💀","👑","🧠","🔧","💣","🪓","🛸","🕹️","🎮","🔥","⚡","🌙","🐸","🐼","🐵","🐧","🦉","🦈","🐙","🦀"];
const games = [
  { id:1, name:"HELLDIVERS™ 2", match:93, mode:"Co-op PvE", pvp:false, pve:true, coop:true, solo:false, max:4, session:"30-60 min", owned:[1,2,3,4], installed:[1,2,4], want:[5], art:"https://images.unsplash.com/photo-1517976487492-5750f3195933?auto=format&fit=crop&w=1200&q=80", desc:"Co-op chaos met korte missies, duidelijke rollen en veel squad momentum. Perfect wanneer de groep snel iets wil spelen zonder lange voorbereiding." },
  { id:2, name:"DEEP ROCK GALACTIC", match:88, mode:"Co-op PvE", pvp:false, pve:true, coop:true, solo:true, max:4, session:"45-90 min", owned:[1,2,3,4,5], installed:[1,2,3,4], want:[], art:"https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1200&q=80", desc:"Mijnbouw, teamwork en paniek in compacte co-op sessies. Sterk voor korte avonden waarin iedereen snel mee kan doen." },
  { id:3, name:"VALHEIM", match:82, mode:"Survival Co-op", pvp:true, pve:true, coop:true, solo:true, max:10, session:"2+ uur", owned:[1,2,4,5], installed:[2,4], want:[3], art:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80", desc:"Survival, bouwen, boss fights en langlopende squad progressie. Goed voor een gedeelde wereld waar je vaker naar terugkeert." },
  { id:4, name:"PROJECT ZOMBOID", match:78, mode:"Survival PvE/PvP", pvp:true, pve:true, coop:true, solo:true, max:16, session:"2+ uur", owned:[1,3,5], installed:[3,5], want:[2,4], art:"https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1200&q=80", desc:"Hardcore survival sandbox voor inside jokes en rampzalige plannen. Minder casual, maar extreem goed voor verhalen." },
  { id:5, name:"RISK OF RAIN 2", match:86, mode:"Co-op Roguelike", pvp:false, pve:true, coop:true, solo:true, max:4, session:"30-75 min", owned:[1,2,4], installed:[1,4], want:[3,5], art:"https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80", desc:"Snelle roguelike runs voor avonden met weinig setup. Actiegericht, herspeelbaar en makkelijk opnieuw te starten." }
];

function App(){
  const [theme,setTheme]=useState("immersion");
  const [selectedGame,setSelectedGame]=useState(null);
  const [selectedUser,setSelectedUser]=useState(null);
  const [partyOpen,setPartyOpen]=useState(false);
  const [partyGame,setPartyGame]=useState(games[0]);
  const [avatarOpen,setAvatarOpen]=useState(false);
  const [myAvatar,setMyAvatar]=useState("🚀");
  const [activeTab,setActiveTab]=useState("home");
  const [quickOpen,setQuickOpen]=useState(false);
  const [toast,setToast]=useState("");
  const [events,setEvents]=useState([{id:1,title:"Helldivers 2 chaos run",time:"Vanavond 20:00",game:"HELLDIVERS™ 2",ready:3}]);
  const [activity,setActivity]=useState(["Kevin started Helldivers 2","Tom joined voice","Shane opened SquadUp"]);
  const [partySlots,setPartySlots]=useState([squad[3],squad[0],null,null]);
  const [ready,setReady]=useState({4:true,1:true});
  const [mood,setMood]=useState("Chaos Run");
  const [status,setStatus]=useState("Forming");
  const smartGame=games[0];
  const push=(m)=>{setToast(m);setActivity(p=>[m,...p].slice(0,7));clearTimeout(window.__toast);window.__toast=setTimeout(()=>setToast(""),1600)};
  const openParty=(game=smartGame)=>{setPartyGame(game);const size=Math.min(Math.max(game.max,4),6);const initial=[squad[3],...game.owned.map(id=>squad.find(u=>u.id===id)).filter(Boolean)];const unique=[...new Map(initial.map(u=>[u.id,u])).values()].slice(0,size);setPartySlots(Array.from({length:size},(_,i)=>unique[i]||null));setReady(Object.fromEntries(unique.map((u,i)=>[u.id,i<2])));setPartyOpen(true)};
  const addToParty=(user)=>{setPartySlots(p=>{if(p.some(s=>s?.id===user.id))return p;const n=[...p];const i=n.findIndex(s=>s===null);if(i!==-1)n[i]=user;return n});push(`${user.name} added to party`)};
  const removeSlot=(index)=>setPartySlots(p=>p.map((s,i)=>i===index?null:s));
  const toggleReady=(id)=>setReady(p=>({...p,[id]:!p[id]}));
  const planGame=(game)=>{setEvents(p=>[{id:Date.now(),title:`${game.name} squad night`,time:"Vandaag 20:30",game:game.name,ready:partySlots.filter(Boolean).length},...p]);push(`${game.name} gepland`)};
  const sendInvites=()=>{setStatus("Ready Check");push(`Invites sent to ${partySlots.filter(Boolean).length} players`)};
  const launchGame=()=>{const filled=partySlots.filter(Boolean);if(!filled.length||!filled.every(u=>ready[u.id])){push("Nog niet iedereen is ready");return}setStatus("In Match");push(`${partyGame.name} launched`)};
  const common={theme,setTheme,squad,games,smartGame,openParty,setSelectedGame,setSelectedUser,events,activity,myAvatar,setAvatarOpen,push,planGame};
  return <div className={`app theme-${theme}`}>
    <DesktopView {...common}/>
    <main className="mobileView"><ThemeStrip theme={theme} setTheme={setTheme}/><MobileLayout {...common}/><NavDock activeTab={activeTab} setActiveTab={setActiveTab} openParty={()=>openParty(smartGame)} setQuickOpen={setQuickOpen}/></main>
    {selectedGame&&<GameModal game={selectedGame} squad={squad} close={()=>setSelectedGame(null)} openParty={openParty} planGame={planGame}/>} 
    {selectedUser&&<UserModal user={selectedUser} close={()=>setSelectedUser(null)} addToParty={addToParty} openParty={()=>openParty(partyGame)}/>} 
    {partyOpen&&<PartyView game={partyGame} setPartyGame={setPartyGame} games={games} squad={squad} slots={partySlots} addToParty={addToParty} removeSlot={removeSlot} ready={ready} toggleReady={toggleReady} mood={mood} setMood={setMood} status={status} sendInvites={sendInvites} launchGame={launchGame} planGame={planGame} close={()=>setPartyOpen(false)}/>} 
    {avatarOpen&&<AvatarModal avatar={myAvatar} setAvatar={setMyAvatar} close={()=>setAvatarOpen(false)} push={push}/>} 
    {quickOpen&&<QuickMenu close={()=>setQuickOpen(false)} openParty={()=>openParty(smartGame)} setActiveTab={setActiveTab} push={push}/>} 
    <div className={`toast ${toast?"show":""}`}>{toast}</div>
  </div>
}

function ThemeStrip({theme,setTheme}){return <div className="themeStrip">{themes.map(t=><button key={t} className={theme===t?"active":""} onClick={()=>setTheme(t)}>{themeNames[t]}</button>)}</div>}
function MobileLayout(p){if(p.theme==="carousel")return <CarouselHome {...p}/>;if(p.theme==="deck")return <DeckHome {...p}/>;if(p.theme==="arcade")return <ArcadeHome {...p}/>;if(p.theme==="lan")return <LanHome {...p}/>;if(p.theme==="grid")return <GridHome {...p}/>;return <section className="screen"><TopBar avatar={p.myAvatar} openAvatar={()=>p.setAvatarOpen(true)} openParty={()=>p.openParty(p.smartGame)}/><Hero game={p.smartGame} openParty={p.openParty} setSelectedGame={p.setSelectedGame}/><SquadRow squad={p.squad} openUser={p.setSelectedUser}/><GameList games={p.games} squad={p.squad} openGame={p.setSelectedGame} openParty={p.openParty}/><Panel title="Planning"><EventList events={p.events}/></Panel><Panel title="Activity"><ActivityList activity={p.activity}/></Panel></section>}
function CarouselHome(p){return <section className="screen"><TopBar avatar={p.myAvatar} openAvatar={()=>p.setAvatarOpen(true)} openParty={()=>p.openParty(p.smartGame)}/><SquadRow squad={p.squad} openUser={p.setSelectedUser} compact/><div className="carouselRail">{p.games.map(g=><button key={g.id} className="carouselCard" onClick={()=>p.setSelectedGame(g)} style={{backgroundImage:`linear-gradient(180deg, transparent, rgba(0,0,0,.82)), url(${g.art})`}}><h2>{g.name}</h2><p>{g.match}% match · {g.mode}</p><span>{g.owned.length}/{p.squad.length} friends own this</span></button>)}</div><Panel title="Planning"><EventList events={p.events}/></Panel></section>}
function DeckHome(p){return <section className="screen deckScreen"><TopBar avatar={p.myAvatar} openAvatar={()=>p.setAvatarOpen(true)} openParty={()=>p.openParty(p.smartGame)}/><h2>Good evening, squad</h2><SquadRow squad={p.squad} openUser={p.setSelectedUser} compact/><button className="wideFeature" onClick={()=>p.openParty(p.games[1])} style={{backgroundImage:`linear-gradient(90deg, rgba(0,0,0,.76), rgba(0,0,0,.2)), url(${p.games[1].art})`}}><small>Continue together</small><strong>{p.games[1].name}</strong></button><GameList games={p.games} squad={p.squad} openGame={p.setSelectedGame} openParty={p.openParty} compact/></section>}
function ArcadeHome(p){return <section className="screen arcadeScreen"><TopBar title="☠ SQUADUP.GG" avatar={p.myAvatar} openAvatar={()=>p.setAvatarOpen(true)} openParty={()=>p.openParty(p.smartGame)}/><div className="arcadePanel"><SquadRow squad={p.squad} openUser={p.setSelectedUser}/></div><button className="startPanel" onClick={()=>p.openParty(p.smartGame)}><h1>WHAT WE PLAYING TONIGHT?</h1><span>PRESS START</span></button><GameList games={p.games} squad={p.squad} openGame={p.setSelectedGame} openParty={p.openParty}/></section>}
function LanHome(p){return <section className="screen lanScreen"><TopBar title="☢ SQUADUP.GG" avatar={p.myAvatar} openAvatar={()=>p.setAvatarOpen(true)} openParty={()=>p.openParty(p.smartGame)}/><button className="terminalPanel" onClick={()=>p.openParty(p.smartGame)}><h1>WHAT ARE WE PLAYING TONIGHT?</h1><p>&gt; START PARTY MODULE</p></button><SquadRow squad={p.squad} openUser={p.setSelectedUser}/><GameList games={p.games} squad={p.squad} openGame={p.setSelectedGame} openParty={p.openParty}/></section>}
function GridHome(p){return <section className="screen gridScreen"><TopBar avatar={p.myAvatar} openAvatar={()=>p.setAvatarOpen(true)} openParty={()=>p.openParty(p.smartGame)}/><div className="gridCards"><Panel title="Squad"><SquadRow squad={p.squad} openUser={p.setSelectedUser} compact/></Panel><Panel title="Mission"><button className="fullButton" onClick={()=>p.openParty(p.smartGame)}>Find match</button></Panel></div><GameList games={p.games} squad={p.squad} openGame={p.setSelectedGame} openParty={p.openParty}/></section>}
function DesktopView(p){return <section className="desktopView"><header className="commandBar"><div className="brand"><Gamepad2/><div><strong>SquadUp<span>.gg</span></strong><small>v0.28 polished</small></div></div><nav className="desktopNav">{["Home","Games","Queue","Squad","Plan","Chat","Profile"].map(l=><button key={l} onClick={()=>l==="Queue"?p.openParty(p.smartGame):p.push(`${l} geopend`)}>{l}</button>)}</nav><button className="desktopPlus" onClick={()=>p.openParty(p.smartGame)}><Plus/></button><button className="avatarButton" onClick={()=>p.setAvatarOpen(true)}>{p.myAvatar}</button><select value={p.theme} onChange={e=>p.setTheme(e.target.value)}>{themes.map(t=><option value={t} key={t}>{themeNames[t]}</option>)}</select></header><main className="desktopMain"><section className="smartCards"><button onClick={()=>p.openParty(p.smartGame)}><Users/><strong>{p.squad.length} friends</strong><span>Start squad queue</span></button><button onClick={()=>p.push("Voice mock geopend")}><Bell/><strong>Voice active</strong><span>Join channel</span></button><button onClick={()=>p.openParty(p.smartGame)}><CalendarDays/><strong>Next event</strong><span>{p.events[0]?.time}</span></button></section><Hero game={p.smartGame} openParty={p.openParty} setSelectedGame={p.setSelectedGame} desktop/><div className="desktopGrid"><Panel title="Recommended games"><GameGrid games={p.games} squad={p.squad} openGame={p.setSelectedGame}/></Panel><Panel title="Squad online"><SquadList squad={p.squad} openUser={p.setSelectedUser}/></Panel><Panel title="Planning"><EventList events={p.events}/></Panel><Panel title="Activity"><ActivityList activity={p.activity}/></Panel></div></main></section>}
function TopBar({title="SQUADUP.GG",avatar,openAvatar,openParty}){return <header className="topBar"><strong>{title}</strong><div><button onClick={openParty}><Zap size={16}/></button><button onClick={openAvatar}>{avatar}</button></div></header>}
function Hero({game,openParty,setSelectedGame,desktop=false}){return <article className={desktop?"hero desktopHero":"hero"} style={{backgroundImage:`linear-gradient(90deg, rgba(0,0,0,.76), rgba(0,0,0,.18)), url(${game.art})`}}><span>Best match tonight</span><h1>{game.name}</h1><p>{game.desc}</p><ModePills game={game}/><div className="heroActions"><button onClick={()=>openParty(game)}>Open party</button><button onClick={()=>setSelectedGame(game)}>Details</button></div></article>}
function ModePills({game}){return <div className="modePills"><span className={game.pvp?"on":""}>PvP {game.pvp?"yes":"no"}</span><span className={game.pve?"on":""}>PvE {game.pve?"yes":"no"}</span><span className={game.coop?"on":""}>Co-op</span><span className={game.solo?"on":""}>Solo</span></div>}
function SquadRow({squad,openUser,compact=false}){return <div className={compact?"squadRow compact":"squadRow"}>{squad.map(u=><button key={u.id} onClick={()=>openUser(u)}><span>{u.avatar}</span><strong>{u.name}</strong><small>{u.status}</small></button>)}</div>}
function SquadList({squad,openUser}){return <div className="squadList">{squad.map(u=><button key={u.id} onClick={()=>openUser(u)}><span>{u.avatar}</span><div><strong>{u.name}</strong><small>{u.status} · {u.game}</small></div></button>)}</div>}
function GameList({games,squad,openGame,openParty}){return <div className="gameList">{games.slice(0,4).map((g,i)=><article key={g.id} onClick={()=>openGame(g)}><b>{i+1}</b><div className="thumb" style={{backgroundImage:`url(${g.art})`}}/><div><strong>{g.name}</strong><small>{g.match}% · {g.mode}</small><small>{g.owned.length}/{squad.length} own · {g.installed.length} installed</small></div><button onClick={e=>{e.stopPropagation();openParty(g)}}>Party</button></article>)}</div>}
function GameGrid({games,squad,openGame}){return <div className="gameGrid">{games.map(g=><button key={g.id} onClick={()=>openGame(g)} style={{backgroundImage:`linear-gradient(180deg, transparent, rgba(0,0,0,.82)), url(${g.art})`}}><strong>{g.name}</strong><span>{g.match}% · {g.mode}</span><small>{g.owned.length}/{squad.length} own · PvP {g.pvp?"yes":"no"}</small></button>)}</div>}
function Panel({title,children}){return <section className="panel"><div className="panelHead"><h3>{title}</h3></div>{children}</section>}
function EventList({events}){return <div className="eventList">{events.map(e=><article key={e.id}><strong>{e.title}</strong><span>{e.time} · {e.ready} ready</span></article>)}</div>}
function ActivityList({activity}){return <div className="activityList">{activity.map((a,i)=><p key={i}>⚡ {a}</p>)}</div>}
function NavDock({activeTab,setActiveTab,openParty,setQuickOpen}){const items=[["home",Home,"Home"],["games",Gamepad2,"Games"],["queue",Zap,"Queue"],["squad",Users,"Squad"],["plan",CalendarDays,"Plan"],["chat",Bell,"Chat"],["profile",User,"Profile"]];return <nav className="navDock">{items.map((it,i)=>{const[id,Icon,label]=it;if(i===3)return <button key="plus" className="centerAction" onClick={()=>setQuickOpen(true)}><Plus/></button>;return <button key={id} className={activeTab===id?"active":""} onClick={()=>id==="queue"?openParty():setActiveTab(id)}><Icon size={18}/><span>{label}</span>{id==="chat"&&<b>3</b>}</button>})}</nav>}
function QuickMenu({close,openParty,setActiveTab,push}){const actions=[["⚡","Start Queue",openParty],["👥","Create Party",openParty],["📣","Ping Squad",()=>push("Squad ping sent")],["📅","Plan Session",()=>setActiveTab("plan")],["🎙️","Join Voice",()=>push("Voice opened")],["➕","Add Friend",()=>setActiveTab("squad")]];return <div className="overlay"><section className="quickMenu"><button className="close" onClick={close}><X/></button><h2>Quick actions</h2><div>{actions.map(([icon,label,fn])=><button key={label} onClick={()=>{fn();close()}}><span>{icon}</span><strong>{label}</strong></button>)}</div></section></div>}
function GameModal({game,squad,close,openParty,planGame}){const names=ids=>ids.map(id=>squad.find(u=>u.id===id)?.name).filter(Boolean).join(", ")||"None";return <div className="overlay"><section className="modal"><button className="close" onClick={close}><X/></button><div className="modalBanner" style={{backgroundImage:`linear-gradient(180deg, transparent, rgba(0,0,0,.85)), url(${game.art})`}}><h2>{game.name}</h2><p>{game.mode} · {game.match}% match</p></div><ModePills game={game}/><p>{game.desc}</p><div className="statsGrid"><div><strong>{game.owned.length}/{squad.length}</strong><span>friends own it</span><small>{names(game.owned)}</small></div><div><strong>{game.installed.length}</strong><span>installed</span><small>{names(game.installed)}</small></div><div><strong>{game.want.length}</strong><span>want to buy</span><small>{names(game.want)}</small></div><div><strong>{game.max}</strong><span>max players</span><small>{game.session}</small></div></div><div className="modalActions"><button onClick={()=>openParty(game)}>Open party</button><button onClick={()=>planGame(game)}>Plan night</button></div></section></div>}
function UserModal({user,close,addToParty,openParty}){return <div className="overlay"><section className="modal"><button className="close" onClick={close}><X/></button><div className="profileTop"><span>{user.avatar}</span><div><small>{user.role}</small><h2>{user.name}</h2><p>{user.status} · {user.game}</p></div></div><p>{user.bio}</p><div className="badges">{user.badges.map(b=><em key={b}>{b}</em>)}</div><div className="modalActions"><button onClick={()=>addToParty(user)}>Invite to party</button><button onClick={openParty}>Open party</button></div></section></div>}
function PartyView({game,setPartyGame,games,squad,slots,addToParty,removeSlot,ready,toggleReady,mood,setMood,status,sendInvites,launchGame,planGame,close}){const candidates=squad.filter(u=>!slots.some(s=>s?.id===u.id));return <div className="overlay partyOverlay"><section className="partyView"><button className="close" onClick={close}><X/></button><header className="partyHero" style={{backgroundImage:`linear-gradient(90deg, rgba(0,0,0,.82), rgba(0,0,0,.2)), url(${game.art})`}}><div><span>Party lobby</span><h1>{game.name}</h1><p>{slots.filter(Boolean).length}/{slots.length} filled · {slots.filter(s=>s&&ready[s.id]).length} ready · {game.mode}</p><ModePills game={game}/></div><div className="partyStatus"><strong>{status}</strong><small>{mood}</small></div></header><div className="partyBody"><main><div className="partyControls"><select value={game.id} onChange={e=>setPartyGame(games.find(g=>g.id===Number(e.target.value)))}>{games.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><div className="moods">{["Chill","Competitive","Chaos Run","Survival","Quick","All Night"].map(m=><button key={m} className={mood===m?"on":""} onClick={()=>setMood(m)}>{m}</button>)}</div></div><div className="partySlots">{slots.map((slot,i)=><article key={i} className={slot?"slot filled":"slot"}>{slot?<><button className="slotRemove" onClick={()=>removeSlot(i)}>×</button><span>{slot.avatar}</span><strong>{slot.name}</strong><small>{game.owned.includes(slot.id)?"Owns game":"Needs game"} · {game.installed.includes(slot.id)?"Installed":"Needs install"}</small><button className={ready[slot.id]?"ready on":"ready"} onClick={()=>toggleReady(slot.id)}>{ready[slot.id]?"✅ Ready":"🟡 Maybe"}</button></>:<><Plus/><strong>Open slot</strong><small>Invite someone</small></>}</article>)}</div><div className="partyActions"><button onClick={sendInvites}>Send invites</button><button onClick={()=>planGame(game)}>Plan event</button><button className="launch" onClick={launchGame}>Launch game</button></div></main><aside><Panel title="Best invites"><div className="candidateList">{candidates.map(u=><button key={u.id} onClick={()=>addToParty(u)}><span>{u.avatar}</span><div><strong>{u.name}</strong><small>{game.owned.includes(u.id)?"Owns game":"Does not own"} · {u.status}</small></div></button>)}</div></Panel><Panel title="Party feed"><ActivityList activity={["Lobby opened","Ready check available","Voice channel suggested"]}/></Panel></aside></div></section></div>}
function AvatarModal({avatar,setAvatar,close,push}){return <div className="overlay"><section className="modal"><button className="close" onClick={close}><X/></button><h2>Choose avatar</h2><div className="avatarGrid">{avatars.map((a,i)=><button key={`${a}-${i}`} className={avatar===a?"on":""} onClick={()=>{setAvatar(a);push("Avatar gekozen")}}>{a}</button>)}</div></section></div>}

createRoot(document.getElementById("root")).render(<App/>);
