import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const games = [
  {id:553850,title:'HELLDIVERS™ 2',tags:['CO-OP','PVE','TPS'],rank:'#4 Steam',price:'€39.99',best:'€27.49',friends:4,squads:2,rating:'4.6/5',img:'https://cdn.cloudflare.steamstatic.com/steam/apps/553850/header.jpg',desc:'Join an elite squad and fight for freedom across hostile planets. Chaotic co-op missions, frantic extraction moments and perfect squad banter.'},
  {id:1245620,title:'ELDEN RING',tags:['PVE','RPG','OPEN WORLD'],rank:'Highly rated',price:'€59.99',best:'€43.29',friends:5,squads:3,rating:'4.7/5',img:'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg',desc:'A vast world of danger, discovery and boss fights. Great for shared progression, build talk and screenshot-worthy moments.'},
  {id:1086940,title:"Baldur's Gate 3",tags:['CO-OP','RPG','STORY'],rank:'#8 RPG',price:'€59.99',best:'€47.99',friends:3,squads:1,rating:'4.9/5',img:'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg',desc:'Gather your party and return to the Forgotten Realms. Deep choices, co-op chaos and long adventure nights.'},
  {id:252490,title:'Rust',tags:['PVP','SURVIVAL','BASE'],rank:'#12 played',price:'€39.99',best:'€29.99',friends:6,squads:4,rating:'4.2/5',img:'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg',desc:'Survive, build and negotiate with questionable friends. Weekly wipes make it perfect for recurring squad stories.'},
  {id:730,title:'Counter-Strike 2',tags:['PVP','TACTICAL','FPS'],rank:'#1 played',price:'Free',best:'Free',friends:7,squads:5,rating:'4.1/5',img:'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg',desc:'Competitive tactical FPS with short sessions and high intensity. Ideal for instant queue nights.'},
  {id:1172470,title:'Apex Legends',tags:['PVP','BR','SQUAD'],rank:'#7 played',price:'Free',best:'Free',friends:3,squads:2,rating:'4.0/5',img:'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg',desc:'Fast battle royale with hero abilities and squad synergy. Great when the group wants action now.'},
  {id:1966720,title:'Lethal Company',tags:['CO-OP','HORROR','FUN'],rank:'Trending',price:'€9.75',best:'€7.49',friends:8,squads:4,rating:'4.6/5',img:'https://cdn.cloudflare.steamstatic.com/steam/apps/1966720/header.jpg',desc:'A hilarious horror co-op scrap hunt where teamwork fails beautifully. Perfect for party voice chaos.'},
  {id:548430,title:'Deep Rock Galactic',tags:['CO-OP','PVE','MINING'],rank:'Squad pick',price:'€29.99',best:'€9.89',friends:4,squads:2,rating:'4.8/5',img:'https://cdn.cloudflare.steamstatic.com/steam/apps/548430/header.jpg',desc:'Dwarven co-op mining, bugs and beer. One of the cleanest squad games for recurring missions.'},
];
const avatars = ['🕶️','🧑‍🚀','🥷','🧙','🤖','🦊','🐺','🐼'];
const friends = ['Kevin','Shane','Tom','Sven','Leah','Mike','Zara','Daan'].map((name,i)=>({name, avatar:avatars[i], status:i%3===0?'In Game':i%3===1?'In Voice':'Online', game:games[i%games.length].title, vol:100-i*7}));
const eventsSeed = [{d:'24',title:'LAN Party',game:'HELLDIVERS™ 2',time:'14:00',going:['Kevin','Shane','Tom'],tasks:['Ethernet switch','Snacks','Extra controller']},{d:'31',title:'Game Night',game:'Rust wipe',time:'20:00',going:['Shane','Sven'],tasks:['Server kiezen','Base plan','Drinks']}];
const themes = {immersion:'Full Immersion',carousel:'Fullscreen Carousel',tactical:'Tactical Command',arcade:'Cyber Arcade'};
function App(){
 const [page,setPage]=useState('home'),[theme,setTheme]=useState('immersion'),[menu,setMenu]=useState(false),[modal,setModal]=useState(null),[party,setParty]=useState(false),[quest,setQuest]=useState(null),[event,setEvent]=useState(eventsSeed[0]);
 const cls=`app theme-${theme} ${menu?'menu-open':''}`;
 return <div className={cls}>
  <aside className="side"><Brand/><Nav page={page} setPage={setPage}/><div className="miniProfile"><div className="avatar">🕶️</div><b>Kevin</b><span>Online</span></div></aside>
  <main className="main"><Top setMenu={setMenu} setPage={setPage}/>{page==='home'&&<Home setPage={setPage} setModal={setModal} setParty={setParty} theme={theme}/>} {page==='explore'&&<Explore theme={theme} setModal={setModal} setQuest={setQuest}/>} {page==='parties'&&<Party setModal={setModal} setParty={setParty}/>} {page==='voice'&&<Voice/>} {page==='calendar'&&<Calendar event={event} setEvent={setEvent}/>} {page==='profile'&&<Profile/>} {page==='settings'&&<Settings theme={theme} setTheme={setTheme}/>}</main>
  <MobileNav setPage={setPage}/>{modal&&<GameModal game={modal} close={()=>setModal(null)} setQuest={setQuest}/>} {party&&<PartyOverlay close={()=>setParty(false)}/>} {quest&&<Quest game={quest} close={()=>setQuest(null)} setParty={setParty}/>} 
 </div>
}
function Brand(){return <div className="brand"><span>ϟ</span><b>SQUADUP.GG</b></div>}
function Nav({page,setPage}){return <nav>{['home','explore','parties','voice','calendar','profile','settings'].map(p=><button className={page===p?'active':''} onClick={()=>setPage(p)} key={p}>{icon(p)}<span>{p}</span></button>)}</nav>}
function icon(p){return {home:'⌂',explore:'◎',parties:'◉',voice:'▥',calendar:'▣',profile:'◌',settings:'⚙'}[p]}
function Top({setMenu,setPage}){return <header><button className="hamb" onClick={()=>setMenu(v=>!v)}>☰</button><input placeholder="Search games, friends, squads..."/><button onClick={()=>setPage('parties')} className="primary">Create Party</button></header>}
function Home({setPage,setModal,setParty,theme}){return <div className="grid home"><Hero setModal={setModal}/><Panel title="Party Lobby" className="partyTiny"><PlayerSlots/><button onClick={()=>setParty(true)} className="primary wide">Open Party</button></Panel><Panel title="Voice Chat"><Voice compact/></Panel><Panel title="Online Friends"><FriendList compact/></Panel><Panel title="Quick Actions"><div className="actions"><button onClick={()=>setParty(true)}>Instant Queue</button><button onClick={()=>setPage('voice')}>Join Voice</button><button onClick={()=>setPage('calendar')}>Plan LAN</button><button>Invite Squad</button></div></Panel><Panel title="Recommended"><Cards setModal={setModal}/></Panel><Panel title="Activity Feed"><Feed/></Panel></div>}
function Hero({setModal}){let g=games[0];return <section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(5,7,15,.95),rgba(5,7,15,.25)),url(${g.img})`}}><span className="badge">TRENDING NOW</span><h1>{g.title}</h1><div>{g.tags.map(t=><em key={t}>{t}</em>)}</div><p>{g.desc}</p><button className="primary" onClick={()=>setModal(g)}>View Game</button><button>Join Parties</button></section>}
function Panel({title,children,className=''}){return <section className={'panel '+className}><h3>{title}</h3>{children}</section>}
function PlayerSlots(){return <div className="slots">{friends.slice(0,4).map((f,i)=><button key={f.name} className="slot"><div className="avatar">{f.avatar}</div><b>{f.name}</b><small>{i===0?'Leader':f.status}</small></button>)}<button className="slot empty">＋<small>Invite</small></button></div>}
function Voice({compact=false}){return <div className={compact?'voice compact':'voice'}>{friends.slice(0,compact?6:8).map(f=><div className="voiceRow" key={f.name}><span className="avatar small">{f.avatar}</span><b>{f.name}</b><span className="mic">▮▮▮▮▮</span>{!compact&&<input type="range" min="0" max="100" defaultValue={f.vol}/>}<small>{f.vol}%</small></div>)}{!compact&&<div className="voiceSettings"><button>Mic Test</button><button>Noise Suppression On</button><button>Echo Cancel On</button><button className="danger">Leave Voice</button></div>}</div>}
function FriendList({compact}){return <div className="friends">{friends.map(f=><button key={f.name}><span className="avatar small">{f.avatar}</span><b>{f.name}</b><small>{f.status} · {compact?f.game.split(' ')[0]:f.game}</small></button>)}</div>}
function Cards({setModal}){return <div className="cards">{games.slice(1,6).map(g=><GameCard key={g.id} g={g} setModal={setModal}/>)}</div>}
function GameCard({g,setModal,setQuest}){return <article className="card" onClick={()=>setModal(g)}><img src={g.img}/><b>{g.title}</b><div className="tagrow">{g.tags.map(t=><em key={t}>{t}</em>)}</div><p>{g.friends} friends · {g.squads} squads</p><footer><span>{g.best}</span>{setQuest&&<button onClick={(e)=>{e.stopPropagation();setQuest(g)}}>Recommend</button>}</footer></article>}
function Feed(){return <ul className="feed"><li>Tom purchased Baldur's Gate 3</li><li>Shane started a Rust party</li><li>Leah unlocked Veteran Helldiver</li><li>Mike joined your squad</li></ul>}
function Explore({theme,setModal,setQuest}){if(theme==='carousel')return <CarouselExplore setModal={setModal} setQuest={setQuest}/>; return <div><div className="filters"><button>For You</button><button>PvP</button><button>PvE</button><button>Co-op</button><button>On Sale</button></div><div className={theme==='tactical'?'listExplore':'exploreGrid'}>{games.concat(games).map((g,i)=><GameCard key={i} g={g} setModal={setModal} setQuest={setQuest}/>)}</div></div>}
function CarouselExplore({setModal,setQuest}){let g=games[1];return <section className="fullCarousel" style={{backgroundImage:`linear-gradient(90deg,rgba(4,6,12,.94),rgba(4,6,12,.1)),url(${g.img})`}}><button className="round">←</button><div><h1>{g.title}</h1><div>{g.tags.map(t=><em key={t}>{t}</em>)}</div><p>{g.friends} friends own this</p><p className="gold">{g.squads} active squads</p><p>★ {g.rating} · {g.desc}</p><div className="price"><span>Steam<br/><b>{g.price}</b></span><span>Best price<br/><b>{g.best}</b></span></div><button className="primary" onClick={()=>setModal(g)}>View Game</button></div><div className="rail"><button onClick={()=>setQuest(g)}>＋<small>Add</small></button><button onClick={()=>setQuest(g)}>ϟ<small>Quest</small></button><button>♡<small>Save</small></button></div></section>}
function Party({setModal,setParty}){return <div className="partyPage"><Hero setModal={setModal}/><Panel title="Squad Lobby"><PlayerSlots/><div className="statusBar"><span>Squad assembled</span><span>4/4 Players</span><span>Voice connected</span></div><button className="primary" onClick={()=>setParty(true)}>Launch Party</button></Panel><Panel title="Party Chat"><Feed/><input placeholder="Message party..."/></Panel><Panel title="Player Insights"><Profile mini/></Panel></div>}
function Calendar({event,setEvent}){return <div className="calendarPage"><Panel title="Plan Hub"><div className="calGrid">{Array.from({length:35},(_,i)=><button onClick={()=>setEvent(eventsSeed[i%2])} className={[24,31].includes(i+1)?'hasEvent':''} key={i}>{i+1}</button>)}</div></Panel><Panel title="Event Preview"><h2>{event.title}</h2><p>{event.d} May · {event.time} · {event.game}</p><div className="going">{event.going.map(n=><span key={n}>{n}</span>)}</div><h4>LAN Sidequests</h4>{event.tasks.map((t,i)=><label className="questLine" key={t}><input type="checkbox" defaultChecked={i===0}/>{t}</label>)}<div className="actions"><button className="primary">Create Event</button><button>Edit</button><button>Delete</button><button>RSVP</button></div></Panel></div>}
function Profile({mini=false}){return <div className={mini?'profile mini':'profile'}><div className="profileHead"><div className="avatar big">🕶️</div><div><h2>Shane <span>Online</span></h2><p>Good vibes, good comms.</p></div></div><div className="stats"><Stat title="Steam Hours" val="1,248h"/><Stat title="Helldivers" val="128h"/><Stat title="Rust" val="94h"/></div><div className="charts"><div className="lineChart"></div><div className="pie"></div></div><FriendList compact/></div>}
function Stat({title,val}){return <div><small>{title}</small><b>{val}</b></div>}
function Settings({theme,setTheme}){return <div className="settings"><Panel title="Theme Gallery"> <div className="themeGallery">{Object.entries(themes).map(([id,name])=><button className={'themePreview '+id+(theme===id?' selected':'')} onClick={()=>setTheme(id)} key={id}><span>{name}</span><small>Preview & apply</small></button>)}</div></Panel><Panel title="Linked Accounts"><div className="links">{['Steam','Discord','Xbox','Google','Apple','Riot'].map(x=><button key={x}><b>{x[0]}</b><span>{x}</span><small>Connect</small></button>)}</div></Panel></div>}
function GameModal({game,close,setQuest}){return <div className="modal"><div className="modalCard"><button className="x" onClick={close}>×</button><img src={game.img}/><h1>{game.title}</h1><div>{game.tags.map(t=><em key={t}>{t}</em>)}</div><p>{game.desc}</p><p>{game.friends} friends own this · {game.squads} active squads · {game.rank}</p><button className="primary" onClick={()=>setQuest(game)}>Recommend as Squad Quest</button><button>Join Parties</button></div></div>}
function PartyOverlay({close}){return <div className="modal"><div className="modalCard partyOverlay"><button className="x" onClick={close}>×</button><h1>Instant Party Started</h1><PlayerSlots/><Voice compact/><button className="primary">Send Push Invites</button></div></div>}
function Quest({game,close,setParty}){return <div className="modal"><div className="modalCard"><button className="x" onClick={close}>×</button><h1>Squad Quest</h1><p>Recommend <b>{game.title}</b> to friends or start a shared buy request.</p>{friends.slice(0,4).map((f,i)=><label className="questLine" key={f.name}><input type="checkbox" defaultChecked={i<2}/>{f.name} {i<2?'checked it':'pending'}</label>)}<button className="primary" onClick={()=>{setParty(true); close();}}>Open Party When Accepted</button></div></div>}
function MobileNav({setPage}){return <div className="mobileNav">{['home','explore','parties','calendar','profile'].map(p=><button onClick={()=>setPage(p)} key={p}>{icon(p)}<small>{p}</small></button>)}</div>}

createRoot(document.getElementById('root')).render(<App/>);
