import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Home, Search, Users, Mic, Library, User, Settings, Bell, Heart, Plus, Play, Share2, X, ChevronLeft, ChevronRight, Gamepad2, Headphones, Crown, CheckCircle2, Zap, ExternalLink, Shield, Send, MessageCircle, Sparkles, Flame, Volume2, LogOut, Link as LinkIcon } from 'lucide-react';
import './styles.css';

const img = {
  helldivers:'https://cdn.cloudflare.steamstatic.com/steam/apps/553850/header.jpg', helldiversHero:'https://cdn.cloudflare.steamstatic.com/steam/apps/553850/library_hero.jpg',
  elden:'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg', eldenHero:'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_hero.jpg',
  bg3:'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg', bg3Hero:'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_hero.jpg',
  rust:'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg', rustHero:'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/library_hero.jpg',
  cyber:'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg', cyberHero:'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_hero.jpg',
  apex:'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg', apexHero:'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/library_hero.jpg',
  witcher:'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg', witcherHero:'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_hero.jpg',
  sea:'https://cdn.cloudflare.steamstatic.com/steam/apps/1172620/header.jpg', hunt:'https://cdn.cloudflare.steamstatic.com/steam/apps/594650/header.jpg', destiny:'https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg', rdr:'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg', deep:'https://cdn.cloudflare.steamstatic.com/steam/apps/548430/header.jpg', lethal:'https://cdn.cloudflare.steamstatic.com/steam/apps/1966720/header.jpg', valheim:'https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg'
};

const games = [
  {id:'helldivers',title:'HELLDIVERS 2',sub:'Managed democracy',art:img.helldivers,hero:img.helldiversHero,price:'€39,99',score:9.1,tags:['Co-op','Shooter','PvE'],theme:'#56f58b',steam:'https://store.steampowered.com/app/553850/HELLDIVERS_2/',desc:'Chaotic co-op missions, frantic extractions and loud squad moments.'},
  {id:'elden',title:'Elden Ring',sub:'Shadow of the Erdtree',art:img.elden,hero:img.eldenHero,price:'€59,99',score:9.8,tags:['RPG','Action','Open World'],theme:'#f1b84b',steam:'https://store.steampowered.com/app/1245620/ELDEN_RING/',desc:'Dark fantasy, boss fights and memorable co-op runs.'},
  {id:'bg3',title:'Baldur’s Gate 3',sub:'Party RPG',art:img.bg3,hero:img.bg3Hero,price:'€59,99',score:9.7,tags:['RPG','Co-op','Story'],theme:'#c679ff',steam:'https://store.steampowered.com/app/1086940/Baldurs_Gate_3/',desc:'Deep choices, party chaos and campaign nights.'},
  {id:'rust',title:'RUST',sub:'Weekly wipe chaos',art:img.rust,hero:img.rustHero,price:'€39,99',score:8.3,tags:['Survival','PvP','Base'],theme:'#ff8a32',steam:'https://store.steampowered.com/app/252490/Rust/',desc:'Raid, build and survive with a squad that never sleeps.'},
  {id:'cyber',title:'Cyberpunk 2077',sub:'Neon open world',art:img.cyber,hero:img.cyberHero,price:'€59,99',score:9.3,tags:['RPG','Open World'],theme:'#00e7ff',steam:'https://store.steampowered.com/app/1091500/Cyberpunk_2077/',desc:'Neon stories, style and cinematic city chaos.'},
  {id:'apex',title:'Apex Legends',sub:'Squad battle royale',art:img.apex,hero:img.apexHero,price:'Free',score:8.6,tags:['FPS','PvP','Squad'],theme:'#ff4f6d',steam:'https://store.steampowered.com/app/1172470/Apex_Legends/',desc:'Fast hero shooter matches for quick squad sessions.'},
  {id:'witcher',title:'The Witcher 3',sub:'Wild Hunt',art:img.witcher,hero:img.witcherHero,price:'€15,99',score:9.6,tags:['RPG','Story'],theme:'#d2d5dd',steam:'https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/',desc:'Monster hunting and a legendary fantasy world.'},
  {id:'hunt',title:'Hunt: Showdown',sub:'Extraction horror',art:img.hunt,hero:img.hunt,price:'€29,99',score:7.9,tags:['Tactical','PvPvE'],theme:'#d25737',steam:'https://store.steampowered.com/app/594650/Hunt_Showdown_1896/',desc:'Tense extraction fights where every sound matters.'},
  {id:'sea',title:'Sea of Thieves',sub:'Pirate sandbox',art:img.sea,hero:img.sea,price:'€39,99',score:8.2,tags:['Co-op','PvP'],theme:'#2fd3c6',steam:'https://store.steampowered.com/app/1172620/Sea_of_Thieves_2024_Edition/',desc:'Sail, loot and create stories with friends.'},
  {id:'deep',title:'Deep Rock Galactic',sub:'Rock and Stone',art:img.deep,hero:img.deep,price:'€29,99',score:9.0,tags:['Co-op','PvE'],theme:'#f59e0b',steam:'https://store.steampowered.com/app/548430/Deep_Rock_Galactic/',desc:'Mining, bugs and rock-solid co-op missions.'},
  {id:'lethal',title:'Lethal Company',sub:'Co-op horror comedy',art:img.lethal,hero:img.lethal,price:'€9,75',score:8.4,tags:['Horror','Co-op'],theme:'#b6f542',steam:'https://store.steampowered.com/app/1966720/Lethal_Company/',desc:'Scrap runs that become hilarious disasters.'},
  {id:'valheim',title:'Valheim',sub:'Viking survival',art:img.valheim,hero:img.valheim,price:'€19,99',score:8.9,tags:['Survival','Co-op'],theme:'#90cdf4',steam:'https://store.steampowered.com/app/892970/Valheim/',desc:'Long-form survival progression for steady squads.'}
];

const avatars = [
  ['soldier-m-01','Viper','Soldier'],['soldier-f-02','Raven','Soldier'],['soldier-m-03','Ghostline','Soldier'],['soldier-f-04','Valkyrie','Soldier'],['soldier-m-05','Breaker','Soldier'],
  ['animal-01','Iron Wolf','Animal'],['animal-02','Ash Lion','Animal'],['animal-03','Grim Bear','Animal'],['animal-04','Night Panther','Animal'],['animal-05','Storm Eagle','Animal'],
  ['legend-01','Volt Reaper','Legendary'],['legend-02','Nova Wraith','Legendary'],['legend-03','Hell Crown','Legendary'],['legend-04','Arc Phantom','Legendary'],['legend-05','Rift Titan','Legendary']
].map(([id,name,type])=>({id,name,type,url:`/avatars/${id}.svg`}));

const baseUsers = ['Shane','Leah','Tom','Maya','Sven','Jaron','Zoe','Rook'].map((name,i)=>({name,avatar:avatars[i%avatars.length].url,ready:i<2,speaking:i===1,role:i===0?'Host':'Member'}));
const nav = [['home',Home,'Home'],['explore',Search,'Explore'],['parties',Users,'Parties'],['voice',Mic,'Voice'],['library',Library,'Library'],['profile',User,'Profile']];
const dailyReasons = ['Hidden gem','4 friends own this','Long not played','Perfect for squads','Weekend deal','Voice-ready pick'];
const trailerUrl = g => `https://www.youtube.com/results?search_query=${encodeURIComponent(`${g.title} official launch trailer`)}`;

function App(){
  const [page,setPage]=useState('home');
  const [selected,setSelected]=useState(null);
  const [wishlist,setWishlist]=useState(['elden','witcher']);
  const [partyGame,setPartyGame]=useState(games[0]);
  const [partyMembers,setPartyMembers]=useState(baseUsers.slice(0,4));
  const [voiceJoined,setVoiceJoined]=useState(true);
  const [ready,setReady]=useState(true);
  const [toast,setToast]=useState('v0.6126 loaded');
  const [notifications,setNotifications]=useState(['Party synced with Voice module','Discord setup guide added']);
  const [modal,setModal]=useState(null);
  const notify=(msg)=>{setNotifications(n=>[msg,...n].slice(0,7));setToast(msg)};
  const toggleWish=(id)=>setWishlist(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);
  const invite=()=>{const pool=baseUsers.filter(u=>!partyMembers.some(m=>m.name===u.name)); const next=pool[0] || {...baseUsers[(partyMembers.length+1)%baseUsers.length],name:`Guest ${partyMembers.length+1}`}; setPartyMembers(m=>[...m,next].slice(0,6)); notify(`${next.name} joined the party`)};
  const leave=()=>{if(partyMembers.length>1){const left=partyMembers[partyMembers.length-1];setPartyMembers(m=>m.slice(0,-1));notify(`${left.name} left the party`) } else notify('Host cannot leave the last active party')};
  const switchGame=(g)=>{setPartyGame(g);notify(`Host changed party game to ${g.title}`);setModal(null)};
  const ctx={page,setPage,selected,setSelected,wishlist,toggleWish,partyGame,setPartyGame,partyMembers,setPartyMembers,voiceJoined,setVoiceJoined,ready,setReady,toast,setToast,notifications,notify,modal,setModal,invite,leave,switchGame};
  return <div className="appShell" style={{'--gameAccent':partyGame.theme}}>
    <Sidebar {...ctx}/>
    <main className="appMain"><Topbar/><MobileHeader/>{page==='home'&&<HomePage {...ctx}/>} {page==='explore'&&<ExplorePage {...ctx}/>} {page==='parties'&&<PartyPage {...ctx}/>} {page==='voice'&&<VoicePage {...ctx}/>} {page==='library'&&<LibraryPage {...ctx}/>} {page==='profile'&&<ProfilePage {...ctx}/>}</main>
    <MobileNav page={page} setPage={setPage}/>
    {selected&&<GameDetail game={selected} close={()=>setSelected(null)} wishlist={wishlist} toggleWish={toggleWish} notify={notify}/>} {modal&&<ActionModal modal={modal} setModal={setModal} games={games} switchGame={switchGame} notify={notify}/>} {toast&&<Toast text={toast} clear={()=>setToast('')}/>}<ChatDock notify={notify}/>
  </div>
}
function Sidebar({page,setPage}){return <aside className="sidebar"><div className="brand"><Zap/><b>SQUADUP</b><small>v0.6126</small></div><nav>{nav.map(([id,Icon,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sideUser"><img src={baseUsers[0].avatar}/><span><b>Shane</b><small>Host online</small></span></div></aside>}
function Topbar(){return <header className="topbar"><div className="search"><Search size={16}/><input placeholder="Search games, parties, friends..."/></div><Bell/><MessageCircle/><img src={baseUsers[0].avatar}/></header>}
function MobileHeader(){return <header className="mobileHeader"><div className="brand"><Zap/><b>SQUADUP</b></div><Bell/><img src={baseUsers[0].avatar}/></header>}
function MobileNav({page,setPage}){return <nav className="mobileNav">{nav.slice(0,5).map(([id,Icon,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={20}/><small>{label}</small></button>)}</nav>}
function Page({children,className=''}){return <section className={`page ${className}`}>{children}</section>}
function Panel({title,children,action}){return <section className="panel"><div className="panelHead"><h2>{title}</h2>{action||<button>View all</button>}</div>{children}</section>}
function HomePage(props){const {setPage,partyGame,partyMembers,invite,leave,voiceJoined,setVoiceJoined,notify}=props;return <Page><section className="homeHero" style={{backgroundImage:`linear-gradient(90deg,#070912 10%,rgba(7,9,18,.55)),url(${partyGame.hero})`}}><p className="eyebrow">CURRENT SQUAD</p><h1>{partyGame.title}</h1><p>{partyGame.desc}</p><div className="heroActions"><button className="primary" onClick={()=>setPage('parties')}>Open Party</button><button onClick={()=>setPage('voice')}>Open Voice</button></div></section><section className="homePartySync"><div><p className="eyebrow">LIVE PARTY PILLS</p><h2>Home synced with Voice</h2><p>Join, leave and invite actions update the same party state across Home, Party and Voice.</p></div><AvatarRail members={partyMembers}/><div className="pillActions"><button className="plusPill" onClick={invite}><Plus/> Invite</button><button className="plusPill" onClick={()=>{setVoiceJoined(!voiceJoined);notify(!voiceJoined?'You joined voice':'You left voice')}}><Headphones/> {voiceJoined?'Leave Voice':'Join Voice'}</button><button className="plusPill danger" onClick={leave}><LogOut/> Simulate Leave</button></div></section><div className="twoCol"><Panel title="Featured for your squad"><GameGrid items={games.slice(0,4)} {...props}/></Panel><Panel title="Party activity"><ActivityFeed items={props.notifications}/></Panel></div></Page>}
function ExplorePage(props){const [heroIdx,setHeroIdx]=useState(0); const daily=useMemo(()=>games.slice(0,3).map((g,i)=>({...g,reason:dailyReasons[(new Date().getDate()+i)%dailyReasons.length]})),[]); const hero=daily[heroIdx%daily.length]; const sections=[['Specials & Offers',games.filter(g=>g.price!=='Free').slice(0,5)],['Popular New Releases',games.slice(1,7)],['Co-op Picks',games.filter(g=>g.tags.includes('Co-op'))],['Hidden Gems',games.slice(7,12)],['Recommended for Your Squad',games.slice().reverse().slice(0,6)]]; useEffect(()=>{const t=setInterval(()=>setHeroIdx(i=>(i+1)%3),6500);return()=>clearInterval(t)},[]); return <Page className="explore"><section className="exploreHero" style={{backgroundImage:`linear-gradient(90deg,#070912 8%,rgba(7,9,18,.35),#070912),url(${hero.hero})`}}><button className="round left" onClick={()=>setHeroIdx((heroIdx+2)%3)}><ChevronLeft/></button><div><p className="eyebrow">Daily Featured · {hero.reason}</p><h1>{hero.title}</h1><p>{hero.desc}</p><button className="primary" onClick={()=>props.setSelected(hero)}>View Details</button><a href={hero.steam} target="_blank">Open Steam</a></div><div className="heroStack">{daily.map((g,i)=><button className={i===heroIdx?'active':''} onClick={()=>setHeroIdx(i)}><img src={g.art}/><span>{g.reason}</span></button>)}</div><button className="round right" onClick={()=>setHeroIdx((heroIdx+1)%3)}><ChevronRight/></button></section><div className="liveNote"><Sparkles/> Live-ready Steam discovery with daily cache + safe fallback data. Deals can later be powered by Steam/ITAD/CheapShark API keys.</div>{sections.map(([title,items])=><Panel title={title} key={title}><GameScroller items={items} {...props}/></Panel>)}</Page>}
function PartyPage(props){const {partyGame,partyMembers,invite,leave,setModal,voiceJoined,setVoiceJoined,ready,setReady,notify}=props;return <Page className="partyPage"><section className="partyArena" style={{backgroundImage:`linear-gradient(110deg,#070912 7%,rgba(7,9,18,.68) 48%,#070912),url(${partyGame.hero})`}}><div className="arenaTop"><span className="liveDot">LIVE PARTY</span><button onClick={()=>setModal('settings')}><Settings/> Settings</button></div><div className="arenaGrid"><div className="partyCopy"><p className="eyebrow">Dynamic Party Arena</p><h1>{partyGame.title}</h1><p>{partyGame.desc}</p><div className="templateRow">{['Ranked Grind','LAN Night','Co-op Run','Horror Squad'].map(t=><button onClick={()=>notify(`Template applied: ${t}`)}>{t}</button>)}</div></div><div className="squadCore"><div className="coreOrb"><Shield/><b>Squad Alpha</b><small>{partyMembers.length}/6 members</small></div><AvatarOrbit members={partyMembers}/></div><aside className="activityCard"><h3>Activity Feed</h3><ActivityFeed items={props.notifications}/></aside></div><div className="quickBar"><button className="primary" onClick={invite}><Plus/> Invite Friends</button><button onClick={()=>{setVoiceJoined(!voiceJoined);notify(!voiceJoined?'You joined the voice channel':'You left the voice channel')}}><Headphones/> {voiceJoined?'Leave Voice':'Join Voice'}</button><button className={ready?'ready active':'ready'} onClick={()=>{setReady(!ready);notify(!ready?'You are ready':'Ready cancelled')}}><CheckCircle2/> {ready?'Ready':'Ready Up'}</button><button onClick={()=>setModal('switchGame')}><Gamepad2/> Switch Game</button><button onClick={()=>window.open('https://discord.com/channels/@me','_blank')}><ExternalLink/> Open Discord</button><button className="danger" onClick={leave}><LogOut/> Simulate Leave</button></div></section></Page>}
function VoicePage(props){const {partyGame,partyMembers,voiceJoined,setVoiceJoined,ready,setReady,notify,setModal}=props;return <Page className="voicePage"><section className="voiceCard" style={{backgroundImage:`linear-gradient(120deg,#070912 10%,rgba(7,9,18,.58)),url(${partyGame.hero})`}}><p className="eyebrow">Discord Voice Hub</p><button className="gameTitleButton" onClick={()=>setModal('switchGame')}><span>{partyGame.title}</span><small>Host can change game</small></button><AvatarRail members={partyMembers}/><div className="voiceControls"><button className="primary" onClick={()=>{setVoiceJoined(!voiceJoined);notify(!voiceJoined?'Connected to Discord voice':'Disconnected from voice')}}><Mic/> {voiceJoined?'Leave Voice':'Join Voice'}</button><button onClick={()=>{setReady(!ready);notify(!ready?'Ready for queue':'No longer ready')}}><CheckCircle2/> {ready?'Ready':'Ready Up'}</button><button onClick={()=>window.open('https://discord.com/channels/@me','_blank')}><ExternalLink/> Open Discord</button></div><DiscordTutorial/></section></Page>}
function LibraryPage(props){return <Page><h1>Library</h1><GameGrid items={games} {...props}/></Page>}
function ProfilePage(props){return <Page><section className="profileHero"><img src={avatars[10].url}/><div><p className="eyebrow">Avatar Vault</p><h1>New 15-avatar set</h1><p>5 soldiers, 5 gritty animals and 5 legendary electric frame avatars. Faces are centered and readable.</p></div></section><div className="avatarGrid">{avatars.map(a=><button onClick={()=>props.notify(`${a.name} selected`)}><img src={a.url}/><b>{a.name}</b><small>{a.type}</small></button>)}</div></Page>}
function GameCard({game,wishlist=[],toggleWish,setSelected,notify}){const liked=wishlist.includes(game.id);return <article className="gameCard" onClick={()=>setSelected(game)} style={{'--cardAccent':game.theme}}><img src={game.art}/><div><b>{game.title}</b><small>{game.tags.join(' · ')}</small><span>{game.price} · {game.score}</span></div><button className={liked?'like liked':'like'} onClick={(e)=>{e.stopPropagation();toggleWish(game.id);notify(liked?'Removed from wishlist':'Added to wishlist')}}><Heart fill={liked?'currentColor':'none'}/></button><a onClick={e=>e.stopPropagation()} href={trailerUrl(game)} target="_blank" className="miniTrailer"><Play size={13}/> Trailer</a></article>}
function GameGrid({items,...props}){return <div className="gameGrid">{items.map(g=><GameCard key={g.id} game={g} {...props}/>)}</div>}
function GameScroller({items,...props}){return <div className="gameScroller">{items.map(g=><GameCard key={g.id} game={g} {...props}/>)}</div>}
function AvatarRail({members}){return <div className="avatarRail">{members.map((m,i)=><div className={`avatarPill ${m.speaking?'speaking':''}`} key={m.name}><img src={m.avatar}/><span>{m.name}</span>{i===0&&<Crown size={14}/>}</div>)}<div className="avatarPill add"><Plus size={18}/></div></div>}
function AvatarOrbit({members}){return <div className="orbit">{members.map((m,i)=><div className={`orbitAvatar a${i} ${m.speaking?'speaking':''}`} key={m.name}><img src={m.avatar}/><span>{m.name}</span></div>)}</div>}
function ActivityFeed({items=[]}){return <div className="activityFeed">{items.map((x,i)=><div key={i}><img src={baseUsers[i%baseUsers.length].avatar}/><span><b>{x}</b><small>{i===0?'now':`${i*3}m ago`}</small></span></div>)}</div>}
function DiscordTutorial(){return <div className="tutorial"><h3>Discord setup</h3><ol><li>Connect your Discord account.</li><li>Add the SquadUp bot to your own server.</li><li>Sync voice channels and select a squad channel.</li><li>Use Join Voice when your party is ready.</li></ol></div>}
function GameDetail({game,close,wishlist,toggleWish,notify}){const liked=wishlist.includes(game.id);return <div className="detailOverlay"><section className="detailPanel" style={{'--detailAccent':game.theme,backgroundImage:`linear-gradient(90deg,#070912 10%,rgba(7,9,18,.62),#070912),url(${game.hero})`}}><div className="detailActions"><button onClick={close}><ChevronLeft/> Back</button><button onClick={()=>{toggleWish(game.id);notify(liked?'Removed from wishlist':'Added to wishlist')}}><Heart fill={liked?'currentColor':'none'}/> Wishlist</button><button onClick={()=>navigator.share?navigator.share({title:game.title,url:game.steam}):notify('Share link copied')}><Share2/> Share</button></div><div className="detailCopy"><p className="eyebrow">{game.tags.join(' · ')}</p><h1>{game.title}</h1><p className="compactDesc">{game.desc}</p><div className="detailStats"><span>{game.score} score</span><span>{game.price}</span><span>Steam</span></div><div className="mediaStrip"><a className="trailerTile" href={trailerUrl(game)} target="_blank" style={{backgroundImage:`linear-gradient(#0005,#0008),url(${game.art})`}}><Play fill="currentColor"/> Official launch trailer</a><a className="trailerTile" href={game.steam} target="_blank" style={{backgroundImage:`linear-gradient(#0005,#0008),url(${game.art})`}}><ExternalLink/> Steam page</a></div></div><aside className="friendsBox"><h3>Play with friends</h3>{baseUsers.slice(0,3).map(u=><div className="friendLine"><img src={u.avatar}/><span>{u.name}</span></div>)}<button className="primary" onClick={()=>notify(`Invite sent for ${game.title}`)}>Invite Squad</button></aside></section></div>}
function ActionModal({modal,setModal,games,switchGame,notify}){return <div className="modalShade"><div className="modalCard"><button className="close" onClick={()=>setModal(null)}><X/></button>{modal==='switchGame'?<><h2>Switch party game</h2><p>Host-only action. Everyone in the party receives a notification.</p><div className="modalGameList">{games.slice(0,8).map(g=><button onClick={()=>switchGame(g)}><img src={g.art}/><span>{g.title}</span></button>)}</div></>:<><h2>Party settings</h2><p>These controls are wired with safe local state until the backend is connected.</p>{['Private party','Friends only visibility','Lock game to host','Sync Discord status'].map(x=><button className="settingLine" onClick={()=>notify(`${x} toggled`)}>{x}<CheckCircle2/></button>)}</>}</div></div>}
function ChatDock({notify}){const [open,setOpen]=useState(false);return <>{open&&<div className="chatBox"><div><b>Party Chat</b><button onClick={()=>setOpen(false)}><X size={16}/></button></div><p>Leah: Ready when you are.</p><p>Tom: Send Discord invite.</p><div className="input"><input placeholder="Message..."/><button onClick={()=>notify('Chat message sent')}><Send size={16}/></button></div></div>}<button className="chatFab" onClick={()=>setOpen(!open)}><MessageCircle/> Chat</button></>}
function Toast({text,clear}){useEffect(()=>{const t=setTimeout(clear,3000);return()=>clearTimeout(t)},[text]);return <div className="toast"><CheckCircle2/> {text}</div>}
createRoot(document.getElementById('root')).render(<App/>);
